name = "JCGERuntime"
uuid = "cc244198-1562-43f7-ad75-589e1d675269"
authors = ["Riccardo Boero <ribo@nilu.no>"]
version = "0.1.0"

[deps]
DualSignals = "e4247b8d-50b5-41ef-b53d-f6e21a6bdac0"
JCGECore = "9fb9d605-0ed3-4980-82c1-f0874844db5d"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DualSignals = "0.1.3"
JCGECore = "0.1"
JuMP = "1"
julia = "1.10"
